// <auto-generated />
using EmployeesAndSalaryWpfApp.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeesAndSalaryWpfApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("EmployeesAndSalaryWpfApp.MVVM.Model.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePlus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EmployeesAndSalaryWpfApp.MVVM.Model.Staffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dateofemployment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headofdepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStaff")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Paycheck")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Staffers");
                });

            modelBuilder.Entity("EmployeesAndSalaryWpfApp.MVVM.Model.Staffer", b =>
                {
                    b.HasOne("EmployeesAndSalaryWpfApp.MVVM.Model.Post", "Post")
                        .WithMany("Staffers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("EmployeesAndSalaryWpfApp.MVVM.Model.Post", b =>
                {
                    b.Navigation("Staffers");
                });
#pragma warning restore 612, 618
        }
    }
}
